name: Repo Monitor
description: A GitHub Action to monitor new issues and pull requests and send notifications to Slack.
author: Shubham Gupta <shubhaamgupta11@gmail.com>
branding:
  icon: zap
  color: blue

inputs:
  task:
    description: Task to run (monitor-issues or monitor-prs).
    required: true
  git_secret:
    description: GitHub token for authentication.
    required: true
    default: ${{ secrets.GIT_SECRET }}
  repo_owner:
    description: Owner of the repository.
    required: true
  repo_name:
    description: Name of the repository.
    required: true
  fetch_data_interval:
    description: How far back to fetch data (e.g., 1 hour, 24 hours).
    required: true
  notifier:
    description: Notification method (slack or discord).
    required: true
  # Slack-specific inputs
  slack_bot_token:
    description: Slack bot token to send notifications.
    required: false
  slack_channel:
    description: The Slack channel to send notifications to.
    required: false
  slack_id_type:
    description: Type of Slack ID (user or group).
    required: false
  slack_id:
    description: Slack ID of the recipient (user or group).
    required: false
  # Discord-specific inputs
  discord_webhook_url:
    description: Discord webhook URL to send notifications.
    required: false


runs:
  using: node16
  main: dist/index.js

outputs:
  result:
    description: Result of the action execution.
