name: Test Action

on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Test Local Action
        uses: ./ # This points to the root of your action's repo
        with:
          task: "monitor-issues"
          git_secret: ${{ secrets.GIT_SECRET }}
          notifier: "discord"
          fetch_data_interval: 2 # in hours
          discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          repo_owner: "facebook"
          repo_name: "react-native"
